### ISSUE TITLE
Question about the result of FsDetView

### ISSUE THREAD

**Issue by Wei-i** [Megvii-BaseDetection/GFSD#3]
Hi, thanks for your great work and source code!
I also want to know why the mAP of FsDetView * drops a lot in your paper, while in FsDetView's paper, on 10-shot COCO setting, it can achieve 12.5.
Is it the same as the difference of Meta R-CNN configuration?
I would be grateful if you could apply for me.

**Comment by Wei-i** [comment]
Another issue I met was that when I run `python test_net.py  --num-gpus 8 MODEL.WEIGHTS log/model_redetect.pth` without `--double-rpn args` to test for performance.
However from the screen, it seems that the parameters of `finetuned_objectness_logits` didn't use?

--log 
[08/13 20:30:22 c2.checkpoint.checkpoint]: The checkpoint contains parameters not used by the model:
  proposal_generator.rpn_head.finetuned_objectness_logits.{weight, bias}

**Comment by zb1439** [comment]
> Hi, thanks for your great work and source code!
> I also want to know why the mAP of FsDetView * drops a lot in your paper, while in FsDetView's paper, on 10-shot COCO setting, it can achieve 12.5.
> Is it the same as the difference of Meta R-CNN configuration?
> I would be grateful if you could apply for me.

Yes. The reason is the same as https://github.com/Megvii-BaseDetection/GFSD/issues/1

**Comment by zb1439** [comment]
> Another issue I met was that when I run `python test_net.py --num-gpus 8 MODEL.WEIGHTS log/model_redetect.pth` without `--double-rpn args` to test for performance.
> However from the screen, it seems that the parameters of `finetuned_objectness_logits` didn't use?
> 
> --log
> [08/13 20:30:22 c2.checkpoint.checkpoint]: The checkpoint contains parameters not used by the model:
> proposal_generator.rpn_head.finetuned_objectness_logits.{weight, bias}

The model will use a general RPN instead of the bias-balanced RPN and load the pretrained RPN's weight if the double-rpn option is disabled.

**Comment by Wei-i** [comment]
> > Another issue I met was that when I run `python test_net.py --num-gpus 8 MODEL.WEIGHTS log/model_redetect.pth` without `--double-rpn args` to test for performance.
> > However from the screen, it seems that the parameters of `finetuned_objectness_logits` didn't use?
> > --log
> > [08/13 20:30:22 c2.checkpoint.checkpoint]: The checkpoint contains parameters not used by the model:
> > proposal_generator.rpn_head.finetuned_objectness_logits.{weight, bias}
> 
> The model will use a general RPN instead of the bias-balanced RPN and load the pretrained RPN's weight if the double-rpn option is disabled.

Thanks!
I am confused if the `bias-balanced RPN` is only used for inference ?

**Comment by zb1439** [comment]
> > > Another issue I met was that when I run `python test_net.py --num-gpus 8 MODEL.WEIGHTS log/model_redetect.pth` without `--double-rpn args` to test for performance.
> > > However from the screen, it seems that the parameters of `finetuned_objectness_logits` didn't use?
> > > --log
> > > [08/13 20:30:22 c2.checkpoint.checkpoint]: The checkpoint contains parameters not used by the model:
> > > proposal_generator.rpn_head.finetuned_objectness_logits.{weight, bias}
> > 
> > 
> > The model will use a general RPN instead of the bias-balanced RPN and load the pretrained RPN's weight if the double-rpn option is disabled.
> 
> Thanks!
> I am confused if the `bias-balanced RPN` is only used for inference ?

Yes, this is mentioned in the implementation details in the supplementary materials.

**Comment by Wei-i** [comment]
> > > > Another issue I met was that when I run `python test_net.py --num-gpus 8 MODEL.WEIGHTS log/model_redetect.pth` without `--double-rpn args` to test for performance.
> > > > However from the screen, it seems that the parameters of `finetuned_objectness_logits` didn't use?
> > > > --log
> > > > [08/13 20:30:22 c2.checkpoint.checkpoint]: The checkpoint contains parameters not used by the model:
> > > > proposal_generator.rpn_head.finetuned_objectness_logits.{weight, bias}
> > > 
> > > 
> > > The model will use a general RPN instead of the bias-balanced RPN and load the pretrained RPN's weight if the double-rpn option is disabled.
> > 
> > 
> > Thanks!
> > I am confused if the `bias-balanced RPN` is only used for inference ?
> 
> Yes, this is mentioned in the implementation details in the supplementary materials.

Thanks！ 
I want to know how to  read your supplementary materials. Could you give me a link ?

**Comment by zb1439** [comment]
The link in readme should be ok.

**Comment by Wei-i** [comment]
@zb1439 I am sorry to disturb you again,  do you have the version of  detectron2's implementation?

**Comment by zb1439** [comment]
> again

Sorry but we do not have a d2 version code. I feel like some minor but careful modifications on config should be almost sufficient for transferring the code. Also please feel free to question.

**Comment by Wei-i** [comment]
> > again
> 
> Sorry but we do not have a d2 version code. I feel like some minor but careful modifications on config should be almost sufficient for transferring the code. Also please feel free to question.

Thanks again for your selfless help :)))
