### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by 2006pmach** [Megvii-BaseDetection/GFSD#5]
Hi, is there an easy way to predict the boxes for a given input image? Something like [this](https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html#inference-demo-with-pre-trained-models)?
Would be very helpful to actually look at the predictions beside computing the metrics... I also checked CVPODS for such a script but it seems to be missing there as well. Thx.

**Comment by zb1439** [comment]
You can refer to https://github.com/Megvii-BaseDetection/cvpods/blob/master/tools/visualize_json_results.py which visualize the saved json file. Also, you can write your own code with fresh input images and visualize them using the APIs provided in cvpods, this python file also provides a good example.
